### ISSUE TITLE
Need a feature to choose the location for reminders

### ISSUE THREAD

**Issue by advaith-unnikrishnan** [kevinjacob2001/CovTrack#2]
Daily Reminders:
- option to choose only specific details such as active cases

**Comment by kevinjacob2001** [comment]
@deepakmkoshy

**Comment by deepakmkoshy** [comment]
Okay, will be working on this issue very soon. Thanks for notifying

**Comment by Aravind1444** [comment]
Okay, this is going to be a useful feature :-)
